name: my_library
description: Personal library management and second-hand books transaction.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+2

environment:
  sdk: ">=2.10.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler:                     # 权限管理
  path_provider:                          # 获取路径
  ai_barcode:                             # 自定义扫码界面
  flutter_barcode_scanner:                # 条码扫描
# barcode_scan: ^3.0.1                    # 新条码扫描(有问题,不可用)
  flutter_launcher_icons:                 # 设置启动图标
# flutter_search_bar:                     # 不太能用的搜索栏(未使用)
# suggestion_search_bar:                  # 带提示的搜索栏(未使用)
  anim_search_bar:                        # 目前在用的搜索栏
  tform:                                  # 表单
  flutter_picker:                         # 选择器
  city_pickers:                           # 城市选择器
  flutter_datetime_picker:                # 日期选择器
  fluttertoast:                           # 小型提示通知
  date_format:                            # 日期格式
  flutter_slidable:                       # List侧滑组件
# shake_animation_widget:                 # 抖动效果
  image_picker:                           # 相册
  crypto:                                 # 加密算法
  shared_preferences:                     # 轻量数据持久化
  url_launcher:                           # 打开外部链接
  fl_chart:                               # 图表
  flutter_staggered_grid_view:            # 更丰富的GridView
# cached_network_image:                   # 网络图片缓存(无法清除缓存,故不使用)
# flutter_screenutil:                     # 屏幕适配方案, 适配不同尺寸屏幕的设计工具
  dio:                                    # 网络请求
  blur:                                   # 高斯模糊组件
  yaml:                                   # 解析yaml文件
  percent_indicator:                      # 进度条
  package_info:                           # 获取项目信息
  loading_indicator_view:                 # 加载动画
  extended_image: ^3.0.0-non-null-safety  # 图片拓展(丰富的拓展操作/图片缓存)
  intro_views_flutter:                    # 引导页
# flutter_intro:                          # 引导操作
  flash:                                  # 显示snackbar
  flutter_native_image:                   # 处理图片(压缩)
  image_cropper:                          # 剪裁图片
  webview_flutter:                        # 网页Webview
  local_auth:                             # 生物识别
  rflutter_alert:                         # 提示框
# pin_code_fields:                        # 验证码输入框



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/txr.jpg
    - assets/images/icon.png
    - assets/NetworkConfig.yaml
    - assets/NetworkConfig.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
